AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RESTApiID:
    Type: String
  RESTApiRootResourceID:
    Type: String
  APIGatewayRoleARN:
    Type: String
  SoundClipsBucket:
    Type: String
Resources:
  ResourceParent:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RESTApiID
      ParentId: !Ref RESTApiRootResourceID
      PathPart: day-of-month
  ResourceChild:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RESTApiID
      ParentId: !Ref ResourceParent
      PathPart: "{day}"
  DayOfMonthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      RequestParameters:
        "method.request.path.day": true
      ResourceId: !Ref ResourceChild
      RestApiId: !Ref RESTApiID
      AuthorizationType: NONE
      Integration:
        Credentials: !Ref APIGatewayRoleARN
        Type: AWS
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - StatusCode: 200
        RequestParameters:
          # For syntax instructions, see https://stackoverflow.com/a/54974119/3606378
          "integration.request.path.day": "method.request.path.day"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/sound-clips/days-of-month/{day}.mp3"
      # Example API Gateway CFN template https://gist.github.com/sihil/93126ca8f319496c921a6077270fcd18
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty