AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RESTApiID:
    Type: String
  RESTApiRootResourceID:
    Type: String
  APIGatewayRoleARN:
    Type: String
  PathPartOfResourceParent:
    Type: String
  MethodIntegrationURI:
    Type: String
Resources:
  ResourceParent:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RESTApiID
      ParentId: !Ref RESTApiRootResourceID
      PathPart: !Ref PathPartOfResourceParent
  ResourceChild:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RESTApiID
      ParentId: !Ref ResourceParent
      PathPart: "{pathVariable}"
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      RequestParameters:
        "method.request.path.pathVariable": true
      ResourceId: !Ref ResourceChild
      RestApiId: !Ref RESTApiID
      AuthorizationType: NONE
      Integration:
        Credentials: !Ref APIGatewayRoleARN
        Type: AWS
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - StatusCode: 200
        # For syntax instructions, see https://stackoverflow.com/a/54974119/3606378
        RequestParameters:
          "integration.request.path.pathVariable": !Sub "method.request.path.pathVariable"
        Uri: !Ref MethodIntegrationURI
      # Example API Gateway CFN template https://gist.github.com/sihil/93126ca8f319496c921a6077270fcd18
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty