AWSTemplateFormatVersion: 2010-09-09
Resources:
  SoundClipsBucket:
    Type: AWS::S3::Bucket
    Properties: {}
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      BinaryMediaTypes:
        - audio/mpeg
        - application/octet-stream
  DeploymentToProd:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - DayOfTheMonthMethodStack
      - DayOfTheWeekMethodStack
      - DigitMethodStack
      - MonthOfTheYearMethodStack
    Properties:
      RestApiId: !Ref RestApi
  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref DeploymentToProd
      StageName: "Prod"
      RestApiId: !Ref RestApi
  APIGRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  DayOfTheMonthMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RESTApiID: !Ref RestApi
        RESTApiRootResourceID: !GetAtt RestApi.RootResourceId
        APIGatewayRoleARN: !GetAtt APIGRole.Arn
        PathPartOfResourceParent: "day-of-month"
        MethodIntegrationURI: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/sound-clips/days-of-month/{pathVariable}.mp3"
      TemplateURL: "method.yml"
  DayOfTheWeekMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RESTApiID: !Ref RestApi
        RESTApiRootResourceID: !GetAtt RestApi.RootResourceId
        APIGatewayRoleARN: !GetAtt APIGRole.Arn
        PathPartOfResourceParent: "day-of-week"
        MethodIntegrationURI: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/sound-clips/days-of-week/{pathVariable}.mp3"
      TemplateURL: "method.yml"
  DigitMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RESTApiID: !Ref RestApi
        RESTApiRootResourceID: !GetAtt RestApi.RootResourceId
        APIGatewayRoleARN: !GetAtt APIGRole.Arn
        PathPartOfResourceParent: "digit"
        MethodIntegrationURI: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/sound-clips/digits/{pathVariable}.mp3"
      TemplateURL: "method.yml"
  MonthOfTheYearMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RESTApiID: !Ref RestApi
        RESTApiRootResourceID: !GetAtt RestApi.RootResourceId
        APIGatewayRoleARN: !GetAtt APIGRole.Arn
        PathPartOfResourceParent: "month-of-year"
        MethodIntegrationURI: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/sound-clips/months-of-year/{pathVariable}.mp3"
      TemplateURL: "method.yml"