AWSTemplateFormatVersion: 2010-09-09
Resources:
  SoundClipsBucket:
    Type: AWS::S3::Bucket
    Properties: {}
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      BinaryMediaTypes:
        - audio/mpeg
        - application/octet-stream
  ProdStage:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - DayOfMonthMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod
  APIGRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  DayOfMonthParent:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt
        - RestApi
        - RootResourceId
      PathPart: day-of-month
  DayOfMonthChild:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref DayOfMonthParent
      PathPart: "{day}"
  DayOfMonthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      RequestParameters:
        "method.request.path.day": true
      ResourceId: !Ref DayOfMonthChild
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      Integration:
        Credentials: !GetAtt APIGRole.Arn
        Type: AWS
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - StatusCode: 200
        RequestParameters:
          # For syntax instructions, see https://stackoverflow.com/a/54974119/3606378
          "integration.request.path.day": "method.request.path.day"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${SoundClipsBucket}/days-of-month/{day}.mp3"
      # Example API Gateway CFN template https://gist.github.com/sihil/93126ca8f319496c921a6077270fcd18
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty