AWSTemplateFormatVersion: 2010-09-09
Resources:
  SoundClipsBucket:
    Type: AWS::S3::Bucket
    Properties: {}
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      BinaryMediaTypes:
        - audio/mpeg
        - application/octet-stream
  DeploymentToProd:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - DayOfTheMonthMethodStack
    Properties:
      RestApiId: !Ref RestApi
  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref DeploymentToProd
      StageName: Prod
      RestApiId: !Ref RestApi
  APIGRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  DayOfTheMonthMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RESTApiID: !Ref RestApi
        RESTApiRootResourceID: !GetAtt RestApi.RootResourceId
        APIGatewayRoleARN: !GetAtt APIGRole.Arn
        SoundClipsBucket: !Ref SoundClipsBucket
      TemplateURL: "method.yml"